executor: "KubernetesExecutor"

# Без Celery/Redis — KubernetesExecutor сам спавнит pod'ы для тасков.
redis:
  enabled: false

# Postgres внутри кластера для метаданных Airflow.
postgresql:
  enabled: true
  primary:
    persistence:
      size: 8Gi

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/avcore/OTUS_MLOps_HomeWorks.git"
    branch: "main"
    rev: "HEAD"
    depth: 1
    subPath: "hw_010/dags"
    wait: 60
  persistence:
    enabled: false   # gitSync кладёт DAG'и в emptyDir, persistence не нужен

# Webserver наружу через LoadBalancer (внешний IP)
webserver:
  service:
    type: LoadBalancer
    ports:
      - name: airflow-ui
        port: 80
        targetPort: 8080
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    password: S9dFVbAzevibqLH
    email: admin@example.com
    firstName: admin
    lastName: user
  resources:
    requests:
      cpu: 200m
      memory: 512Mi

scheduler:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi

triggerer:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

env:
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "False"
