apiVersion: v1
kind: Service
metadata:
  name: fraud-api
  namespace: fraud
  labels:
    app: fraud-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: fraud-api
